### ISSUE TITLE
Extract all configurations to jsons

### ISSUE THREAD

**Issue by eduardoneira** [eduardoneira/SistemasDistribuidos_TPFinal#13]
Llevarse todo lo configurable a los json

**Comment by LuisAli22** [comment]
Ya pasé las constantes a un json en Web server. No me fijé el resto de CMC. Pero me parece que ya está todo en archivos config.json. Por ahí ya se puede cerrar este issue. Querés que vea algo referido a las constantes y cosas configurables? Por ahí hay algo escondido. Se hizo grande la cantidad de código. Debería mirar un archivo tras otro para buscar mejoras. Más adeltante voy a escribir un par de issues nuevas para refactorizar el código en general, separar el código del tp (código de producción) del código de las pruebas, etc.

**Comment by eduardoneira** [comment]
si esto me aprece que quedo bastante bien en general
