### ISSUE TITLE
Face recognizer Id Vrs Database Id 

### ISSUE THREAD

**Issue by LuisAli22** [eduardoneira/SistemasDistribuidos_TPFinal#18]
Cuando reinicio face_recognizer, vuelve a asignar Id desde 1 en adelante, pero en la base de datos persiste los ids de corridas anteriores. Entonces puede haber discrepancias entre ids guardados en la base de datos y ids que da como resultado el face recognizer por ejemplo cuando predice.

**Comment by eduardoneira** [comment]
Tendriamos q persistir el dato de la id en un archivo para mi, asi no vuelve a pasar

**Comment by eduardoneira** [comment]
ahora todo son archivos y persistidos en db, no hay nada en memoria asi que no deberia volver este problema
